// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMWFjgDjndB_fRMI8zLA2lHepk9TsNgiQ',
    appId: '1:732645429919:web:4ee8820f6a6788bbd508aa',
    messagingSenderId: '732645429919',
    projectId: 'control-weather-app',
    authDomain: 'control-weather-app.firebaseapp.com',
    storageBucket: 'control-weather-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-yfo_G6ZM7VJofsAPmj0nheXSABfHfrQ',
    appId: '1:732645429919:android:682407723ea5121ed508aa',
    messagingSenderId: '732645429919',
    projectId: 'control-weather-app',
    storageBucket: 'control-weather-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbCABQwwNQN0mDUvts7aLw_ssXVRP3fak',
    appId: '1:732645429919:ios:661c485dbe94760fd508aa',
    messagingSenderId: '732645429919',
    projectId: 'control-weather-app',
    storageBucket: 'control-weather-app.appspot.com',
    iosClientId: '732645429919-bo7tof8m03utkkifg5md1ltr0jhi0sn0.apps.googleusercontent.com',
    iosBundleId: 'com.example.weathera',
  );
}
